version: '3.9'
services:
  web:
    build: .
    container_name: maze-production
    restart: unless-stopped    # This makes it restart after reboot
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production